### ISSUE TITLE
Improve Docker tags

### ISSUE THREAD

**Issue by markhobson** [markhobson/docker-maven-chrome#11]
We currently support the following tags:

* `latest` (jdk-8/Dockerfile)
* `jdk-11` (jdk-11/Dockerfile)
* `jdk-16` (jdk-16/Dockerfile)

These should become:

* `jdk-8` (jdk-8/Dockerfile)
* `jdk-11` (jdk-11/Dockerfile)
* `jdk-16`, `latest` (jdk-16/Dockerfile)

This requires:

1. [Multiple Docker tags per build](https://github.com/docker/hub-feedback/issues/341), which doesn't appear to be working in Docker Hub. [Using a post push hook](https://windsock.io/automated-docker-image-builds-with-multiple-tags/) may be a suitable workaround.
1. Switching `latest` from `jdk-8` to `jdk-16`. This will break users currently reliant upon this tag.

**Comment by mark-r-m** [comment]
Docker Hub and Docker Cloud should both seamlessly support multiple tags, like "latest,{\1}.{\2}.{\3},{\1}.{\2},{\1}" - that's the most common use case for both! I understand the Cloud is where Docker want us to go, but for those of us staying on Hub, you should support this too.

**Comment by markhobson** [comment]
It appears that Docker Hub does now support multiple tags per build. I've added `jdk-8` as an alias for `latest` which is jdk-8/Dockerfile.

I'll update the docs to ask those using `latest` to start using `jdk-8` instead, so we can switch `latest` to `jdk-15` at a later date.

**Comment by arturds** [comment]
you can add a chrome version on tag too, since last update many of my testes start to fail

**Comment by markhobson** [comment]
@arturds You can see #2 for a previous discussion about tagging against specific Chrome versions. In summary, we don't since Chrome updates automatically and this image tries to reflect this.

**Comment by amony-ot** [comment]
Hi Mark,

When i'm using your chrome images its throwing an timeout exception. Even i selected all three java versions.

ChromeDriver was started successfully.
**[1617639057.803][SEVERE]: Timed out receiving message from renderer: 600.000**

**Comment by markhobson** [comment]
Hi @amony-ot, this sounds similar to #20 but I'm not seeing these messages any more. Could you raise a new issue with more details please?

**Comment by amony-ot** [comment]
It worked On Jan 15, but the same image is not working recently. When i update it to Firefox its working without any issues. Not sure whether the latest update to 89 version causing this issue.

**Comment by markhobson** [comment]
@amony-ot It's certainly a Chrome issue, so you won't experience it with Firefox. Could you raise a new issue with more details, rather than comment on this unrelated one please?

**Comment by markhobson** [comment]
I've now switched `latest` to point to `jdk-16` rather than `jdk-8`. Please update any image references that need to be fixed at JDK 8 to use the Docker tag `jdk-8` - I've added a note to the README.
