### ISSUE TITLE
Support JDK 12

### ISSUE THREAD

**Issue by heruan** [markhobson/docker-maven-chrome#12]
Maven docker images for JDK 12 switched from Debian to another OS and the provided Dockerfile does not work with the latest Maven image.

**Comment by markhobson** [comment]
Thanks for raising this issue @heruan. You're right that the base image has changed:

* `maven:3.6.1-jdk-11` extends `debian:stretch`
* `maven:3.6.1-jdk-12` extends `oraclelinux:7-slim`

I've quickly tried installing Chrome on Oracle Linux with the following Dockerfile:

```
FROM maven:3.6.1-jdk-12

RUN echo $'\
[google-chrome]\n\
name=google-chrome\n\
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64\n\
enabled=1\n\
gpgcheck=1\n\
gpgkey=https://dl.google.com/linux/linux_signing_key.pub'\
> /etc/yum.repos.d/google-chrome.repo
RUN yum install google-chrome-stable
```

Unfortunately it appears to be missing the `liberation-fonts` package:

```
Error: Package: google-chrome-stable-75.0.3770.142-1.x86_64 (google-chrome)
           Requires: liberation-fonts
```

It's not clear to me how best to obtain this package. I see that [under RHEL it can be installed using the optional repository](https://access.redhat.com/discussions/3674041) but `subscription-manager` is unavailable under Oracle Linux. Any tips welcome.

**Comment by markhobson** [comment]
Chrome install appears to have fixed itself. New `markhobson/maven-chrome:jdk-12` tag now available in Docker Hub.
