### ISSUE TITLE
Usage with protractor

### ISSUE THREAD

**Issue by egwepas** [markhobson/docker-maven-chrome#13]
I'm using our image to run protractor tests (from within maven using maven-frontend-plugin).

Do you know if there is a way to tell protractor to use the webdriver that is bundled within your docker image ?

We are currently doing a "webdriver update" that will, most of the time, download an incompatible (version-wise) webdriver.

**Comment by markhobson** [comment]
Hi, have you tried setting [`chromeDriver`](https://github.com/angular/protractor/blob/master/lib/config.ts#L76) in the Protractor `conf.js` file? Something like this may work:

```
exports.config = {
  chromeDriver: '/usr/bin/chromedriver'
}
```

**Comment by egwepas** [comment]
It workds, indeed, thanks a lot for your quick answer !

It might be a good idea to add that into your readme.

**Comment by markhobson** [comment]
Great, glad it worked okay!

Not sure about documenting this as the image isn't Protractor specific. If it becomes a common problem then I will reconsider.

**Comment by markhobson** [comment]
Added to README, thanks!
