### ISSUE TITLE
Comment about chrome and /dev/shm : freezes and timeout

### ISSUE THREAD

**Issue by egwepas** [markhobson/docker-maven-chrome#14]
I know this isn't your fault but I'd like to trace this here for future users.

google-chrome makes use of /dev/shm for runtime data. In docker images this mount point is small by default (64mo), and this causes chrome to crash / freeze.

Using protractor and jasmine, there is no error message and it looks like a timeout.

The fix for this is either :
 - Increase the SHM size (or mount it to the host's shm)
 - Start chrome with flag --disable-dev-shm-usage

That's it.

Feel free to close this or eventually add it to your README for poor souls like us that lost 4 days on that issue ;-)

**Comment by markhobson** [comment]
Added to README, thanks!
