### ISSUE TITLE
Broken docker image (latest)

### ISSUE THREAD

**Issue by gtricot** [markhobson/docker-maven-chrome#17]
I've been using markhobson/maven-chrome:latest image for a while now.
Since MR #16, the image is broken : ChromeDriver version is 77 but Chrome version is 76.

I checked that running command line :
```
/opt/google/chrome/google-chrome --version 
```
That printed :
```
Google Chrome 76.0.3809.100
```

**Comment by ohmybrew** [comment]
Same issue here, driver is 77, Chrome is 76.

**Comment by markhobson** [comment]
Apologies for that, it appears that Docker Hub was caching layers during the build. I've turned off caching and rebuilt:

```
$ docker run -it markhobson/maven-chrome sh -c "google-chrome --version && chromedriver --version"
Google Chrome 77.0.3865.90 
ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})
```
