### ISSUE TITLE
Error in invoking Chrome driver

### ISSUE THREAD

**Issue by AnandMaven** [markhobson/docker-maven-chrome#18]
Hi,

This is the error that I am getting when I am trying to execute the test cases on Chrome in headless mode.

Unable to load browser: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)

These are the Chrome Options that I am using
chromeOptions.addArguments("--no-sandbox");
                        chromeOptions.addArguments("--headless");
                        chromeOptions.addArguments("--disable-dev-shm-usage");
                        chromeOptions.addArguments("--disable-setuid-sandbox");
                        chromeOptions.addArguments("disable-infobars");
                        chromeOptions.addArguments("--disable-extensions");

And here is the Docker file
FROM maven:3.6.1-jdk-8

# Google Chrome

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update -qqy \
	&& apt-get -qqy install google-chrome-stable \
	&& rm /etc/apt/sources.list.d/google-chrome.list \
	&& rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
	&& sed -i 's/"$HERE\/chrome"/"$HERE\/chrome" --no-sandbox/g' /opt/google/chrome/google-chrome

# ChromeDriver

#ARG CHROME_DRIVER_VERSION=77.0.3865.40
ARG CHROME_DRIVER_VERSION=78.0.3904.70
RUN wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip \
	&& rm -rf /opt/chromedriver \
	&& unzip /tmp/chromedriver_linux64.zip -d /opt \
	&& rm /tmp/chromedriver_linux64.zip \
	&& mv /opt/chromedriver /opt/chromedriver-$CHROME_DRIVER_VERSION \
	&& chmod 755 /opt/chromedriver-$CHROME_DRIVER_VERSION \
	&& ln -fs /opt/chromedriver-$CHROME_DRIVER_VERSION /usr/bin/chromedriver

WORKDIR /app
COPY . /app

ENTRYPOINT ["/bin/bash", "-c", "mvn -Durl=https://www.google.com test"]

**Comment by markhobson** [comment]
Hi, the latest image was for Chrome 77. It looks like you're building a custom image for Chrome 78? I'm not sure I can support that but I've upgraded this one to Chrome 78 if that helps.

**Comment by AnandMaven** [comment]
But with 77 also it was giving the same error so I changed the version and tried it.

Not on putting the updated commands in the docker file gives me the following output in Power Shell and then it kind of hangs with nothing further.

Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

**Comment by AnandMaven** [comment]
It is now working for me.

**Comment by markhobson** [comment]
Great, no probs.
