### ISSUE TITLE
chrome latest version 

### ISSUE THREAD

**Issue by totovelo10** [markhobson/docker-maven-chrome#19]
Hello @BlackPepperSoftware,
My jenkinsfile contains: 
`pipeline {
   agent { 
     docker { image 'markhobson/maven-chrome:latest' } 
  }
...
`
when i launch a google-chrome --version I obtain

`+ google-chrome --version

mkdir: cannot create directory ‘//.local’: Permission denied

touch: cannot touch '//.local/share/applications/mimeapps.list': No such file or directory

Google Chrome **77.0.3865.90**
`
Then when i want to launch chromedriver : 

`Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (session not created: This version of ChromeDriver only supports Chrome version 80
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ad484080e6f5', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-7-amd64', java.version: '1.8.0_222'
Driver info: driver.version: ProvideNewDriver
`

**Comment by markhobson** [comment]
Hi, are you sure that you've pulled the latest version of this image? The current Chrome version is indeed 80:

```
$ docker run -it --rm markhobson/maven-chrome google-chrome --version
Google Chrome 80.0.3987.106
```

**Comment by markhobson** [comment]
I haven't heard back so assuming this is no longer an issue. Please reopen if it is.
