### ISSUE TITLE
receiving lots of Timed out receiving message from renderer: 0.100

### ISSUE THREAD

**Issue by dummys** [markhobson/docker-maven-chrome#20]
Hi,

I'm running your latest image, in headless mode, and I get a lot of  warning like this:

`[1585150564.457][SEVERE]: Timed out receiving message from renderer: 0.100`

Do you get the same in your testing ?

**Comment by markhobson** [comment]
Hi, yes I'm afraid so. You can read more about it here:
https://stackoverflow.com/questions/60114639/timed-out-receiving-message-from-renderer-0-100-log-messages-using-chromedriver

**Comment by dummys** [comment]
Do you plan to use chrome v81 ?

**Comment by markhobson** [comment]
Yes, once it's out of beta.

**Comment by markhobson** [comment]
Upgraded the image to Chrome 83 and these warnings have now gone.
