### ISSUE TITLE
Suggestion: JDK 15

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [markhobson/docker-maven-chrome#26]
Includes:

JDK 15 (AdoptOpenJDK)
Maven 3.6.3
Chrome 86+
ChromeDriver 86+

**Comment by markhobson** [comment]
Hi @DmitriyKapeliukh, thanks for the suggestion. I'll take a look at adding JDK 15 support, although it'll probably be OpenJDK.

**Comment by markhobson** [comment]
`markhobson/maven-chrome:jdk-15` is now available on Docker Hub.

**Comment by DmitriyKapeliukh** [comment]
> `markhobson/maven-chrome:jdk-15` is now available on Docker Hub.

@markhobson Thank you!
