### ISSUE TITLE
Upgrade chrome driver to 87.0.4280.88 

### ISSUE THREAD

**Issue by shubgene** [markhobson/docker-maven-chrome#27]
I am using jdk 11 image and I am getting below exception 

    org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'jenkins-automation-5-m47q4-pqtg0-15swp', ip: '10.168.184.157', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.203-156.332.amzn2.x86_64', java.version: '11.0.9.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.66, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: /tmp/.com.google.Chrome.T3rZOJ}, goog:chromeOptions: {debuggerAddress: localhost:39721}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 100c7b77bf9a219bac634144c79d4bc2

**Comment by markhobson** [comment]
Hi, I'm not clear whether than exception is due to an older version of ChromeDriver as it works fine for me locally. I've upgraded Chrome & ChromeDriver to the latest versions though - let me know if that fixes your problem.

**Comment by shubgene** [comment]
HI Mark , 

Thanks for taking this.  I have proceeded ahead by setting this below line of code:
options.addArguments("--disable-dev-shm-usage");

This resolved my issue.  I will test again .for now I will close this issue.

**Comment by markhobson** [comment]
Hi @shubgene, glad you've resolved your issue - sounds possibly related to the [problem mentioned in the README](https://github.com/markhobson/docker-maven-chrome#chrome-crashes).
