### ISSUE TITLE
Is there a way to set SCREEN_WIDTH & SCREEN_HEIGHT when not running test in headless mode?

### ISSUE THREAD

**Issue by mohitrathi92** [markhobson/docker-maven-chrome#29]
I tried the below command,

DOCKER_IMAGE=markhobson/maven-chrome:jdk-8
docker pull $DOCKER_IMAGE
docker run -t -v "$PWD":/usr/src -w /usr/src -v $HOME/.m2:/root/.m2 --network host -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1480 $DOCKER_IMAGE mvn clean install -DsuiteFile=$testSuite

**Comment by markhobson** [comment]
Hi, setting the screen size using these environment variables seems to be a [feature of docker-selenium](https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution), which this image doesn't inherit. What is the use-case here?

**Comment by mohitrathi92** [comment]
Thanks for the confirmation.
