### ISSUE TITLE
 Timed out receiving message from renderer: 600.00

### ISSUE THREAD

**Issue by Jjaayyaa** [markhobson/docker-maven-chrome#33]
I am trying to use the jdk-11 version of this image, however, the tests are failing to start. 

It started 6 days ago when I see there were some changes committed to this repository. 

It seems to me that the version changes in the driver and chrome are not properly working. Please investigate.

`INFO: Created user preferences directory.
Starting ChromeDriver 92.0.4515.43 (8c61b7e2989f2990d42f859cac71319137787cce-refs/branch-heads/4515@{#306}) on port 4064
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1626902883.276][SEVERE]: Timed out receiving message from renderer: 600.000`

**Comment by markhobson** [comment]
Apologies, I didn't seem to get a notification when this issue was raised.

That `SEVERE` log message is actually just a warning - see #20. What errors are you encountering?

**Comment by markhobson** [comment]
Closing until further information.
