### ISSUE TITLE
Suggestion: can you please add the Firefox browser in this docker image?

### ISSUE THREAD

**Issue by vivek-407** [markhobson/docker-maven-chrome#35]
Suggestion: Can you please add Firefox browser in this docker image?

**Comment by markhobson** [comment]
I'd rather keep browsers in separate images. Have you seen [markhobson/docker-maven-firefox](https://github.com/markhobson/docker-maven-firefox)? Although it does need updating.

**Comment by markhobson** [comment]
Closing until further feedback.
