### ISSUE TITLE
Bug: ChromeDriver 98.0.4758.48 has a bug

### ISSUE THREAD

**Issue by janmekota** [markhobson/docker-maven-chrome#36]
Hello,
there was a bug in ChromeDriver 98.0.4758.48 https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999.
It is fixed now in https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.102/
Would it be possible to rebuild the docker images (especially `jdk-11`) in the docker hub with the fix, please?
Thank you in advance

**Comment by markhobson** [comment]
Apologies for not replying sooner, I didn't receive a notification.

ChromeDriver has now been upgraded to 100.0.4896.60 - does that resolve your problem?

**Comment by markhobson** [comment]
Closing until further feedback.
