### ISSUE TITLE
getting error , please help 

### ISSUE THREAD

**Issue by Rivsinghal12** [markhobson/docker-maven-chrome#38]
[0KRunning with gitlab-runner 15.0.0 (febb2a09)[0;m
[0K  on prodport-runner QiHVcDfb[0;m
section_start:1656048225:prepare_executor
[0K[0K[36;1mPreparing the "kubernetes" executor[0;m[0;m
[0KUsing Kubernetes namespace: gitlab-runner-shared[0;m
[0KUsing Kubernetes executor with image markhobson/maven-chrome ...[0;m
[0KUsing attach strategy to execute scripts...[0;m
section_end:1656048225:prepare_executor
[0Ksection_start:1656048225:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Waiting for pod gitlab-runner-shared/runner-qihvcdfb-project-107-concurrent-04vsh5 to be running, status is Pending
	ContainersNotInitialized: "containers with incomplete status: [init-permissions]"
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
Waiting for pod gitlab-runner-shared/runner-qihvcdfb-project-107-concurrent-04vsh5 to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
Running on runner-qihvcdfb-project-107-concurrent-04vsh5 via gitlab-runner-shared-8594f766bd-z64sx...

section_end:1656048232:prepare_script
[0Ksection_start:1656048232:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/prodport/automation-framework/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 6878e529 as develop...[0;m

[32;1mSkipping Git submodules setup[0;m

section_end:1656048233:get_sources
[0Ksection_start:1656048233:restore_cache
[0K[0K[36;1mRestoring cache[0;m[0;m
[32;1mChecking cache for default...[0;m
Downloading cache.zip from https://prodport-gitlab-runner.s3.dualstack.ap-south-1.amazonaws.com/gitlab-runner/runner/QiHVcDfb/project/107/default[0;m 
[32;1mSuccessfully extracted cache[0;m

section_end:1656048235:restore_cache
[0Ksection_start:1656048235:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[32;1m$ mvn test[0;m
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< ProdPort:ProdPort >--------------------------
[INFO] Building ProdPort 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/4.1.1/selenium-java-4.1.1.pom
Progress (1): 2.7/4.8 kB
Progress (1): 4.8 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-java/4.1.1/selenium-java-4.1.1.pom (4.8 kB at 4.2 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/4.1.1/selenium-api-4.1.1.pom
Progress (1): 2.1 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-api/4.1.1/selenium-api-4.1.1.pom (2.1 kB at 6.0 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/4.1.1/selenium-chrome-driver-4.1.1.pom
Progress (1): 2.7/3.4 kB
Progress (1): 3.4 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chrome-driver/4.1.1/selenium-chrome-driver-4.1.1.pom (3.4 kB at 9.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service-annotations/1.0.1/auto-service-annotations-1.0.1.pom
Progress (1): 2.3 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service-annotations/1.0.1/auto-service-annotations-1.0.1.pom (2.3 kB at 6.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service-aggregator/1.0.1/auto-service-aggregator-1.0.1.pom
Progress (1): 2.7/4.3 kB
Progress (1): 4.3 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service-aggregator/1.0.1/auto-service-aggregator-1.0.1.pom (4.3 kB at 12 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.pom
Progress (1): 2.7/3.1 kB
Progress (1): 3.1 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.pom (3.1 kB at 8.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/google/auto/auto-common/1.2/auto-common-1.2.pom
Progress (1): 2.7/4.4 kB
Progress (1): 4.4 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/auto/auto-common/1.2/auto-common-1.2.pom (4.4 kB at 13 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chromium-driver/4.1.1/selenium-chromium-driver-4.1.1.pom
Progress (1): 2.7/3.0 kB
Progress (1): 3.0 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-chromium-driver/4.1.1/selenium-chromium-driver-4.1.1.pom (3.0 kB at 8.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-json/4.1.1/selenium-json-4.1.1.pom
Progress (1): 2.3 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-json/4.1.1/selenium-json-4.1.1.pom (2.3 kB at 6.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/4.1.1/selenium-remote-driver-4.1.1.pom
Progress (1): 2.7/7.1 kB
Progress (1): 5.5/7.1 kB
Progress (1): 7.1 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-remote-driver/4.1.1/selenium-remote-driver-4.1.1.pom (7.1 kB at 20 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-buffer/4.1.70.Final/netty-buffer-4.1.70.Final.pom
Progress (1): 1.6 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-buffer/4.1.70.Final/netty-buffer-4.1.70.Final.pom (1.6 kB at 4.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-parent/4.1.70.Final/netty-parent-4.1.70.Final.pom
Progress (1): 4.1/69 kB
Progress (1): 8.2/69 kB
Progress (1): 12/69 kB 
Progress (1): 16/69 kB
Progress (1): 20/69 kB
Progress (1): 24/69 kB
Progress (1): 28/69 kB
Progress (1): 32/69 kB
Progress (1): 36/69 kB
Progress (1): 40/69 kB
Progress (1): 45/69 kB
Progress (1): 49/69 kB
Progress (1): 53/69 kB
Progress (1): 57/69 kB
Progress (1): 61/69 kB
Progress (1): 65/69 kB
Progress (1): 69 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-parent/4.1.70.Final/netty-parent-4.1.70.Final.pom (69 kB at 126 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-common/4.1.70.Final/netty-common-4.1.70.Final.pom
Progress (1): 4.1/12 kB
Progress (1): 8.2/12 kB
Progress (1): 12/12 kB 
Progress (1): 12 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-common/4.1.70.Final/netty-common-4.1.70.Final.pom (12 kB at 36 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/4.1.70.Final/netty-codec-http-4.1.70.Final.pom
Progress (1): 3.3 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/4.1.70.Final/netty-codec-http-4.1.70.Final.pom (3.3 kB at 9.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport/4.1.70.Final/netty-transport-4.1.70.Final.pom
Progress (1): 1.9 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport/4.1.70.Final/netty-transport-4.1.70.Final.pom (1.9 kB at 5.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-resolver/4.1.70.Final/netty-resolver-4.1.70.Final.pom
Progress (1): 1.6 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-resolver/4.1.70.Final/netty-resolver-4.1.70.Final.pom (1.6 kB at 4.7 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec/4.1.70.Final/netty-codec-4.1.70.Final.pom
Progress (1): 4.1/4.4 kB
Progress (1): 4.4 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-codec/4.1.70.Final/netty-codec-4.1.70.Final.pom (4.4 kB at 13 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-handler/4.1.70.Final/netty-handler-4.1.70.Final.pom
Progress (1): 3.6 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-handler/4.1.70.Final/netty-handler-4.1.70.Final.pom (3.6 kB at 10 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-classes-epoll/4.1.70.Final/netty-transport-classes-epoll-4.1.70.Final.pom
Progress (1): 2.1 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-classes-epoll/4.1.70.Final/netty-transport-classes-epoll-4.1.70.Final.pom (2.1 kB at 6.2 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-unix-common/4.1.70.Final/netty-transport-native-unix-common-4.1.70.Final.pom
Progress (1): 4.1/26 kB
Progress (1): 8.2/26 kB
Progress (1): 12/26 kB 
Progress (1): 16/26 kB
Progress (1): 20/26 kB
Progress (1): 24/26 kB
Progress (1): 26 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-unix-common/4.1.70.Final/netty-transport-native-unix-common-4.1.70.Final.pom (26 kB at 71 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-classes-kqueue/4.1.70.Final/netty-transport-classes-kqueue-4.1.70.Final.pom
Progress (1): 2.1 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-classes-kqueue/4.1.70.Final/netty-transport-classes-kqueue-4.1.70.Final.pom (2.1 kB at 6.2 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-api/1.9.1/opentelemetry-api-1.9.1.pom
Progress (1): 1.8 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-api/1.9.1/opentelemetry-api-1.9.1.pom (1.8 kB at 3.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-context/1.9.1/opentelemetry-context-1.9.1.pom
Progress (1): 1.6 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-context/1.9.1/opentelemetry-context-1.9.1.pom (1.6 kB at 4.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-exporter-logging/1.9.1/opentelemetry-exporter-logging-1.9.1.pom
Progress (1): 2.2 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-exporter-logging/1.9.1/opentelemetry-exporter-logging-1.9.1.pom (2.2 kB at 6.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk/1.9.1/opentelemetry-sdk-1.9.1.pom
Progress (1): 2.2 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk/1.9.1/opentelemetry-sdk-1.9.1.pom (2.2 kB at 6.2 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-common/1.9.1/opentelemetry-sdk-common-1.9.1.pom
Progress (1): 2.0 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-common/1.9.1/opentelemetry-sdk-common-1.9.1.pom (2.0 kB at 5.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-semconv/1.9.1-alpha/opentelemetry-semconv-1.9.1-alpha.pom
Progress (1): 1.8 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-semconv/1.9.1-alpha/opentelemetry-semconv-1.9.1-alpha.pom (1.8 kB at 5.3 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-trace/1.9.1/opentelemetry-sdk-trace-1.9.1.pom
Progress (1): 2.4 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-trace/1.9.1/opentelemetry-sdk-trace-1.9.1.pom (2.4 kB at 7.0 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-api-metrics/1.9.1-alpha/opentelemetry-api-metrics-1.9.1-alpha.pom
Progress (1): 2.0 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-api-metrics/1.9.1-alpha/opentelemetry-api-metrics-1.9.1-alpha.pom (2.0 kB at 5.6 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-metrics/1.9.1-alpha/opentelemetry-sdk-metrics-1.9.1-alpha.pom
Progress (1): 2.0 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-metrics/1.9.1-alpha/opentelemetry-sdk-metrics-1.9.1-alpha.pom (2.0 kB at 5.9 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-logs/1.9.1-alpha/opentelemetry-sdk-logs-1.9.1-alpha.pom
Progress (1): 2.2 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-logs/1.9.1-alpha/opentelemetry-sdk-logs-1.9.1-alpha.pom (2.2 kB at 6.5 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.0/jackson-databind-2.13.0.pom
Progress (1): 4.1/15 kB
Progress (1): 8.2/15 kB
Progress (1): 12/15 kB 
Progress (1): 15 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.0/jackson-databind-2.13.0.pom (15 kB at 41 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-base/2.13.0/jackson-base-2.13.0.pom
Progress (1): 4.1/9.7 kB
Progress (1): 8.2/9.7 kB
Progress (1): 9.7 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-base/2.13.0/jackson-base-2.13.0.pom (9.7 kB at 28 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.13.0/jackson-bom-2.13.0.pom
Progress (1): 4.1/17 kB
Progress (1): 8.2/17 kB
Progress (1): 12/17 kB 
Progress (1): 16/17 kB
Progress (1): 17 kB   
                   
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.13.0/jackson-bom-2.13.0.pom (17 kB at 49 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.0/jackson-annotations-2.13.0.pom
Progress (1): 4.1/6.1 kB
Progress (1): 6.1 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.0/jackson-annotations-2.13.0.pom (6.1 kB at 18 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.0/jackson-core-2.13.0.pom
Progress (1): 4.1/5.5 kB
Progress (1): 5.5 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.0/jackson-core-2.13.0.pom (5.5 kB at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.9.1/opentelemetry-sdk-extension-autoconfigure-spi-1.9.1.pom

Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-safari-driver/4.1.1/selenium-safari-driver-4.1.1.jar (25 kB at 6.0 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-support/4.1.1/selenium-support-4.1.1.jar (201 kB at 47 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.12.2/byte-buddy-1.12.2.jar (3.7 MB at 856 kB/s)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ProdPort ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /builds/prodport/automation-framework/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ ProdPort ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 23 source files to /builds/prodport/automation-framework/target/classes
[INFO] /builds/prodport/automation-framework/src/main/java/com/ProdPort/Library/CoreFrameWork.java: /builds/prodport/automation-framework/src/main/java/com/ProdPort/Library/CoreFrameWork.java uses or overrides a deprecated API.
[INFO] /builds/prodport/automation-framework/src/main/java/com/ProdPort/Library/CoreFrameWork.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ProdPort ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ ProdPort ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 16 source files to /builds/prodport/automation-framework/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ ProdPort ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[Configuration] [WARN] Detected a static method [com.ProdPort.Library.CoreFrameWork.LaunchDriverAndGet()]. Static configuration methods can cause  unexpected behavior.
[Configuration] [WARN] Detected a static method [com.ProdPort.Library.CoreFrameWork.BackToHomePage()]. Static configuration methods can cause  unexpected behavior.
[Configuration] [WARN] Detected a static method [com.ProdPort.Library.CoreFrameWork.LaunchDriverAndGet()]. Static configuration methods can cause  unexpected behavior.
[Configuration] [WARN] Detected a static method [com.ProdPort.Library.CoreFrameWork.BackToHomePage()]. Static configuration methods can cause  unexpected behavior.
 INFO [main] (WebDriverManager.java:966)- Using chromedriver 102.0.5005.61 (resolved driver for Chrome 102)
 INFO [main] (WebDriverManager.java:1292)- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
 INFO [main] (Downloader.java:127)- Downloading https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
 INFO [main] (Downloader.java:188)- Extracting driver from compressed file chromedriver_linux64.zip
 INFO [main] (WebDriverManager.java:1021)- Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/102.0.5005.61/chromedriver
Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 46546
Only local connections are allowed.
Pleas[1656048269.540][SEVERE]: bind() failed: Cannot assign requestede s eaddress (99)
e https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Tests run: 12, Failures: 1, Errors: 0, Skipped: 11, Time elapsed: 3.92 sec <<< FAILURE! - in TestSuite
LaunchDriverAndGet(regeression.suit.UserManagmentScript)  Time elapsed: 3.453 sec  <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'runner-qihvcdfb-project-107-concurrent-04vsh5', ip: '192.168.213.82', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.181-99.354.amzn2.x86_64', java.version: '18.0.1.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]

Results :

Failed tests: 
regeression.suit.UserManagmentScript.LaunchDriverAndGet(regeression.suit.UserManagmentScript)
  Run 1: UserManagmentScript>CoreFrameWork.LaunchDriverAndGet:63 » SessionNotCreated Co...
  Run 2: PASS
  Run 3: PASS
  Run 4: PASS

Tests run: 6, Failures: 1, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.782 s
[INFO] Finished at: 2022-06-24T05:24:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project ProdPort: There are test failures.
[ERROR] 
[ERROR] Please refer to /builds/prodport/automation-framework/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

section_end:1656048270:step_script
[0Ksection_start:1656048270:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m

section_end:1656048271:cleanup_file_variables
[0K[31;1mERROR: Job failed: command terminated with exit code 1
[0;m

**Comment by Rivsinghal12** [comment]
it is wokring fine on locat , not able to understand why its not working on gitlab server

**Comment by markhobson** [comment]
This seems more like a GitLab configuration issue than a problem with this image, but I'd look closer at this error message:

```
Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
(unknown error: DevToolsActivePort file doesn't exist)
```

This [seems to suggest](https://stackoverflow.com/questions/71704028/unknown-error-devtoolsactiveport-file-doesnt-exist-launching-chromedriver-usin) that the build isn't using Chrome installed in this image, since that does specify `--no-sandbox`.
