### ISSUE TITLE
Request : docker image with tag

### ISSUE THREAD

**Issue by fchetouani** [markhobson/docker-maven-chrome#4]
Good morning Mr Hobson

I use your docker image markhobson/maven-chrome to run Java automated UI tests 
with maven and jasmine, it works fine.

There is no tag for your image, please **could it be possible to tag your image with a release number ?**
like this we are sure that our continuous integration can not break when you update your image.

Thank you

**Comment by markhobson** [comment]
Hi, what tags would you like to see? This is a duplicate of #2 - see the comments there for the reasons why we don't currently support tags.

**Comment by markhobson** [comment]
Duplicate of #2.

**Comment by fchetouani** [comment]
I understand, thank you for your reply.

So, I close the issue.
