### ISSUE TITLE
Can't run test in Chrome 106

### ISSUE THREAD

**Issue by bacnn0701** [markhobson/docker-maven-chrome#41]
Chrome update new version, after pull image & create session Chrome, can not run test in this. I'm using jdk 16

**Comment by markhobson** [comment]
Hi, I'm not clear how you're using this image. Chrome shouldn't auto-update inside the image and there's not a JDK16 image. Can you provide instructions to reproduce?

**Comment by bacnn0701** [comment]
I am using two your image : chrome & firefox to run my test case, before this I always run successfully schedule every day but today, image chrome failed many times with no reason, image firefox still success. I update jdk 18,  file yml config as below:, can you help check image again?

e2e-chrome-test:
  image: markhobson/maven-chrome:latest
  stage: test
  script:
    - mvn clean test -Dtest.suite=filetest.xml
  artifacts:
    paths:
      - target

**Comment by markhobson** [comment]
What error message are you getting?

**Comment by markhobson** [comment]
That error can be ignored - see #20.

Can you provide a minimal project that reproduces the problem locally with this Docker image?

**Comment by bacnn0701** [comment]
Sorry I don't have any minimal project to help you reproduces the problems, I will try to follow #20 to resolve the problems.

**Comment by markhobson** [comment]
Okay, it's hard to help without more information or being able to reproduce the problem. I'll close this until then.
