### ISSUE TITLE
Some reason jdk8 still takes default java 20

### ISSUE THREAD

**Issue by vijayila1980** [markhobson/docker-maven-chrome#46]
Hello...
I am new to this community,
I just started using concourse. unfortunately we have very old code for selenium tests, some reason we could not find the compatible cucumber versions for java 19 / 20.
So though of using below. Though I I set the tags as jdk-8, still I see default its taking java 20.

logs:
openjdk 20 2023-03-21
OpenJDK Runtime Environment Temurin-20+36 (build 20+36)
OpenJDK 64-Bit Server VM Temurin-20+36 (build 20+36, mixed mode, sharing)
+ mvn --version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /usr/share/maven
Java version: 20, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.14.311-233.529.amzn2.x86_64", arch: "amd64", family: "unix"

name: selenium-e2e-smoke
    plan:
      - get: git-automation
      - config:
          image_resource:
            source:
              repository: markhobson/maven-chrome
              tags: jdk-8
            type: docker-image
          inputs:
            - name: E2EAutomation
          outputs:
            - name: reports
          platform: linux

Please suggest am I doing anything wrong here.

**Comment by vijayila1980** [comment]
I tried to change the image name to 
 - get: git-automation
      - config:
          image_resource:
            source:
              repository: markhobson/docker-maven-chrome
              tags: jdk-8
            type: docker-image

then I see below error:

version is missing from previous step

**Comment by markhobson** [comment]
Hi, sorry for the delayed reply. I'm not familiar with Concourse CI, but the Docker image `markhobson/maven-chrome:jdk-8` does indeed contain Java 8:

```
$ docker run --rm -it markhobson/maven-chrome:jdk-8 java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)
```

I'd guess that you have a Concourse configuration problem.

**Comment by vijayila1980** [comment]
Thank you, I just created a custom Image. its working now.. thanks again.
