### ISSUE TITLE
Upgrade ChromeDriver to 2.37

### ISSUE THREAD

**Issue by andreas-mausch** [markhobson/docker-maven-chrome#5]
Hi thanks for creating this image. We use it in our CI and it works like a charm.
We also use WebDriverManager which reports

```
INFO: Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
Mar 16, 2018 11:56:16 AM io.github.bonigarcia.wdm.WebDriverManager getLatest
INFO: Latest version of [chromedriver] is 2.37
```

later we get 

```
Caused by: org.openqa.selenium.SessionNotCreatedException: 
session not created exception: Chrome version must be >= 64.0.3282.0
  (Driver info: chromedriver=2.37.543610 (afd36256570660b5a2f0e4dbd1b040f3dcfe9cb5),platform=Linux 4.4.44-39.55.amzn1.x86_64 x86_64)
```

We managed to fix it by setting the ChromeDriver version to 2.35. However, we would like to stay up to date, so could you please update and publish the image to use the newest ChromeDriver/Chrome?

Thank you

**Comment by markhobson** [comment]
Hi Andreas, no problem, glad you find it useful! I've upgraded ChromeDriver to 2.37 and a new build is available on Docker Hub.

**Comment by andreas-mausch** [comment]
Thanks Mark, that was quick.
