### ISSUE TITLE
Plans for an JDK21 image?

### ISSUE THREAD

**Issue by stephanlukasczyk** [markhobson/docker-maven-chrome#50]
Hi,

Do you have plans to provide a JDK21 image, too?

Thank you in advance.

**Comment by markhobson** [comment]
Once an upstream image is available I'll add a `jdk-21` variant.

**Comment by kzander91** [comment]
[3.9.4-eclipse-temurin-21](https://hub.docker.com/layers/library/maven/3.9.4-eclipse-temurin-21/images/sha256-7357a177f1690195d3a7b2b7c09a66833217d8b9dae8f9e66d70ed6aa3275717?context=explore) is now available.

**Comment by markhobson** [comment]
Thanks, I'll do this after getting on top of the [other recent changes](https://github.com/markhobson/docker-maven-chrome/pull/49#issuecomment-1710758280).

**Comment by markhobson** [comment]
I've now added a `jdk-21` variant after resolving the Chrome/ChromeDriver upgrades. Hope that helps!
