### ISSUE TITLE
Break due to Upgrade Maven to 3.5.3 

### ISSUE THREAD

**Issue by fchetouani** [markhobson/docker-maven-chrome#6]
Good morning Mark

Due to the last image update, our continuous integration is broken.

here is the error message
+ cp ../deployment-conf/concourse/settings.default.xml /root/.m2/settings.xml
cp: cannot create regular file '/root/.m2/settings.xml': No such file or directory

I suppose that the reason is the maven upgrade to 3.5.3
could it be possible that in your Dockefile you create the directory /root/.m2 (if not exists)

Thank you for your help

**Comment by markhobson** [comment]
Hi, it looks like the `~/.m2` directory is [now created by the entrypoint](https://github.com/carlossg/docker-maven/commit/d2e41bb4b98f827e7929eb01578538854a61726b):

```
$ docker run -it --entrypoint ls maven:3.5.2 -l /root/.m2
total 0
$ docker run -it --entrypoint ls maven:3.5.3 -l /root/.m2
ls: cannot access '/root/.m2': No such file or directory
```

Running the entrypoint:

```
$ docker run -it maven:3.5.3 ls -l /root/.m2
total 8
-rw-r--r-- 1 root root 194 Mar 19 20:05 copy_reference_file.log
-rw-r--r-- 1 root root 327 Mar 19 20:05 settings-docker.xml
```

Are you overriding the entrypoint in your CI build?

**Comment by markhobson** [comment]
Also worth reading this part of their docs if you're wanting to configure `settings.xml`:
https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image

**Comment by fchetouani** [comment]
Good morning Mark

Thank you very much for your time and the links.

So I close the issue.

**Comment by fchetouani** [comment]
Thanks Mark, your link about maven configuration in Docker gives a nice solution.
